-- Plugin-specific highlight groups for Dracula Pro

local M = {}

-- Helper function to tint colors (darken/brighten)
local function tint(color, percent)
  if not color or color == 'NONE' then return 'NONE' end
  local r = tonumber(color:sub(2, 3), 16)
  local g = tonumber(color:sub(4, 5), 16)
  local b = tonumber(color:sub(6), 16)
  if not r or not g or not b then return 'NONE' end

  local blend = function(component)
    component = math.floor(component * (1 + percent))
    return math.min(math.max(component, 0), 255)
  end

  return string.format('#%02x%02x%02x', blend(r), blend(g), blend(b))
end

function M.get(c, opts)
  -- Custom derived colors for plugins
  local custom = {
    error_bg = tint(c.error, -0.8),
    warn_bg = tint(c.orange, -0.8),
    info_bg = tint(c.blue, -0.7),
    hint_bg = tint(c.purple, -0.7),
    purple1 = tint(c.purple, -0.2),
    gray = c.comment,
    gold = c.yellow,
    blue_bg = tint(c.blue, -0.8),
    diff_change_bg = tint(c.blue, -0.85),
    diff_text_bg = tint(c.blue, -0.75),
  }

  -- LSP Kind highlights (for completion items, breadcrumbs, etc.)
  local lsp_kinds = {
    ['module'] = { fg = c.orange },
    ['snippet'] = { fg = c.purple },
    ['folder'] = { fg = c.fg },
    ['color'] = { fg = c.fg },
    ['file'] = 'Directory',
    ['text'] = '@string',
    ['method'] = '@method',
    ['function'] = '@function',
    ['constructor'] = '@constructor',
    ['field'] = '@field',
    ['variable'] = '@variable',
    ['property'] = '@property',
    ['unit'] = '@constant',
    ['value'] = '@variable',
    ['enum'] = '@type',
    ['keyword'] = '@keyword',
    ['reference'] = '@parameter.reference',
    ['constant'] = '@constant',
    ['struct'] = '@structure',
    ['event'] = '@variable',
    ['operator'] = '@operator',
    ['namespace'] = '@namespace',
    ['package'] = '@include',
    ['string'] = '@string',
    ['number'] = '@number',
    ['boolean'] = '@boolean',
    ['array'] = '@repeat',
    ['object'] = '@type',
    ['key'] = '@field',
    ['null'] = '@symbol',
    ['enumMember'] = '@field',
    ['class'] = '@lsp.type.class',
    ['interface'] = '@lsp.type.interface',
    ['typeParameter'] = '@lsp.type.parameter',
  }

  return {
    -- WhichKey
    WhichKey = { fg = c.purple },
    WhichKeySeperator = { fg = c.blue },
    WhichKeyGroup = { fg = c.cyan },
    WhichKeyDesc = { fg = c.fg },
    WhichKeyFloat = { bg = c.bg_float },

    -- GitSigns
    SignAdd = { fg = c.git.add },
    SignChange = { fg = c.git.change },
    SignDelete = { fg = c.git.delete },
    GitSignsAdd = { fg = c.git.add },
    GitSignsChange = { fg = c.git.change },
    GitSignsDelete = { fg = c.git.delete },
    GitSignsUntracked = { fg = c.git.ignore },
    GitSignsAddInline = 'DiffText',
    GitSignsChangeInline = 'DiffChange',
    GitSignsDeleteInline = 'DiffDelete',

    -- Telescope
    TelescopeSelection = { bg = custom.blue_bg },
    TelescopeSelectionCaret = { fg = c.cyan, bg = custom.blue_bg },
    TelescopeMatching = { fg = c.orange, bold = true, italic = true },
    TelescopeBorder = { fg = c.border },
    TelescopeNormal = { fg = c.fg, bg = c.bg },
    TelescopePromptTitle = { fg = c.orange },
    TelescopePromptPrefix = { fg = c.blue },
    TelescopeResultsTitle = { fg = c.orange },
    TelescopePreviewTitle = { fg = c.orange },
    TelescopePromptCounter = { fg = c.cyan },
    TelescopePreviewHyphen = { fg = c.cyan },

    -- NvimTree
    NvimTreeFolderIcon = { fg = custom.gold },
    NvimTreeIndentMarker = { fg = custom.gray },
    NvimTreeNormal = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    NvimTreeVertSplit = { fg = c.bg_sidebar, bg = c.bg_sidebar },
    NvimTreeFolderName = { fg = c.fg_sidebar },
    NvimTreeOpenedFolderName = { fg = c.fg_sidebar, bold = true, italic = true },
    NvimTreeEmptyFolderName = { fg = c.comment, italic = true },
    NvimTreeGitIgnored = { fg = c.comment, italic = true },
    NvimTreeImageFile = { fg = c.fg },
    NvimTreeSpecialFile = { fg = c.orange },
    NvimTreeEndOfBuffer = { fg = c.comment },
    NvimTreeCursorLine = { bg = c.bg_highlight },
    NvimTreeGitStaged = { fg = c.git.add },
    NvimTreeGitNew = { fg = c.git.ignore },
    NvimTreeGitRenamed = { fg = c.git.change },
    NvimTreeGitDeleted = { fg = c.git.delete },
    NvimTreeGitMerge = { fg = c.git.change },
    NvimTreeGitDirty = { fg = c.git.ignore },
    NvimTreeSymlink = { fg = c.blue },
    NvimTreeRootFolder = { fg = c.fg, bold = true },
    NvimTreeExecFile = { fg = c.green },
    NvimTreeLspDiagnosticsError = 'DiagnosticError',
    NvimTreeLspDiagnosticsWarning = 'DiagnosticWarn',
    NvimTreeLspDiagnosticsInformation = 'DiagnosticInfo',
    NvimTreeLspDiagnosticsInfo = 'DiagnosticInfo',
    NvimTreeLspDiagnosticsHint = 'DiagnosticHint',

    -- Neo-tree
    NeoTreeFolderIcon = { fg = custom.gold },
    NeoTreeIndentMarker = { fg = custom.gray },
    NeoTreeNormal = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    NeoTreeFileName = { fg = c.fg_sidebar },
    NeoTreeFileNameOpened = { fg = c.fg, bold = true, italic = true },
    NeoTreeDirectoryName = { fg = c.fg_sidebar },
    NeoTreeDirectoryIcon = { fg = custom.gold },
    NeoTreeVertSplit = { fg = c.bg_sidebar, bg = c.bg_sidebar },
    NeoTreeWinSeparator = { fg = c.bg_sidebar, bg = c.bg_sidebar },
    NeoTreeOpenedFolderName = { fg = c.fg, bold = true, italic = true },
    NeoTreeEmptyFolderName = { fg = c.comment, italic = true },
    NeoTreeGitIgnored = { fg = c.comment, italic = true },
    NeoTreeDotfile = { fg = c.comment, italic = true },
    NeoTreeHiddenByName = { fg = c.comment, italic = true },
    NeoTreeEndOfBuffer = { fg = c.comment },
    NeoTreeCursorLine = { bg = c.bg_highlight },
    NeoTreeGitStaged = { fg = c.git.add },
    NeoTreeGitUntracked = { fg = c.git.ignore },
    NeoTreeGitDeleted = { fg = c.git.delete },
    NeoTreeGitModified = { fg = c.git.change },
    NeoTreeSymbolicLinkTarget = { fg = c.blue },
    NeoTreeRootName = { fg = c.fg, bold = true },
    NeoTreeTitleBar = { fg = c.bg, bg = c.fg, bold = true },

    -- Barbar (buffer tabs)
    BufferCurrent = { fg = c.fg, bg = c.bg },
    BufferCurrentIndex = { fg = c.fg, bg = c.bg },
    BufferCurrentMod = { fg = c.warning, bg = c.bg },
    BufferCurrentSign = { fg = c.blue, bg = c.bg },
    BufferCurrentTarget = { fg = c.cyan, bg = c.bg, bold = true },
    BufferVisible = { fg = c.fg, bg = c.bg },
    BufferVisibleIndex = { fg = c.fg, bg = c.bg },
    BufferVisibleMod = { fg = c.warning, bg = c.bg },
    BufferVisibleSign = { fg = custom.gray, bg = c.bg },
    BufferVisibleTarget = { fg = c.cyan, bg = c.bg, bold = true },
    BufferInactive = { fg = custom.gray, bg = c.bg_dark },
    BufferInactiveIndex = { fg = custom.gray, bg = c.bg_dark },
    BufferInactiveMod = { fg = c.warning, bg = c.bg_dark },
    BufferInactiveSign = { fg = custom.gray, bg = c.bg_dark },
    BufferInactiveTarget = { fg = c.cyan, bg = c.bg_dark, bold = true },

    -- Indent Blankline
    IndentBlanklineContextChar = { fg = c.fg_gutter },
    IndentBlanklineContextStart = { sp = c.fg_gutter, underline = true },
    IndentBlanklineChar = { fg = c.bg_highlight },
    IblIndent = { fg = c.bg_highlight },
    IblScope = { fg = c.fg_gutter },

    -- nvim-cmp (completion menu)
    CmpItemAbbrMatch = { fg = c.blue, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.blue, italic = true },
    CmpItemAbbrDeprecated = { fg = custom.gray, strikethrough = true },
    CmpItemKindVariable = lsp_kinds['variable'],
    CmpItemKindModule = lsp_kinds['module'],
    CmpItemKindSnippet = lsp_kinds['snippet'],
    CmpItemKindFolder = lsp_kinds['folder'],
    CmpItemKindColor = lsp_kinds['color'],
    CmpItemKindFile = lsp_kinds['file'],
    CmpItemKindText = lsp_kinds['text'],
    CmpItemKindMethod = lsp_kinds['method'],
    CmpItemKindFunction = lsp_kinds['function'],
    CmpItemKindConstructor = lsp_kinds['constructor'],
    CmpItemKindField = lsp_kinds['field'],
    CmpItemKindProperty = lsp_kinds['property'],
    CmpItemKindUnit = lsp_kinds['unit'],
    CmpItemKindValue = lsp_kinds['value'],
    CmpItemKindEnum = lsp_kinds['enum'],
    CmpItemKindKeyword = lsp_kinds['keyword'],
    CmpItemKindReference = lsp_kinds['reference'],
    CmpItemKindConstant = lsp_kinds['constant'],
    CmpItemKindStruct = lsp_kinds['struct'],
    CmpItemKindEvent = lsp_kinds['event'],
    CmpItemKindOperator = lsp_kinds['operator'],
    CmpItemKindNamespace = lsp_kinds['namespace'],
    CmpItemKindPackage = lsp_kinds['package'],
    CmpItemKindString = lsp_kinds['string'],
    CmpItemKindNumber = lsp_kinds['number'],
    CmpItemKindBoolean = lsp_kinds['boolean'],
    CmpItemKindArray = lsp_kinds['array'],
    CmpItemKindObject = lsp_kinds['object'],
    CmpItemKindKey = lsp_kinds['key'],
    CmpItemKindNull = lsp_kinds['null'],
    CmpItemKindEnumMember = lsp_kinds['enumMember'],
    CmpItemKindClass = lsp_kinds['class'],
    CmpItemKindInterface = lsp_kinds['interface'],
    CmpItemKindTypeParameter = lsp_kinds['typeParameter'],

    -- Navic (breadcrumbs)
    NavicIconsFile = lsp_kinds['file'],
    NavicIconsModule = lsp_kinds['module'],
    NavicIconsNamespace = lsp_kinds['namespace'],
    NavicIconsPackage = lsp_kinds['package'],
    NavicIconsClass = lsp_kinds['class'],
    NavicIconsMethod = lsp_kinds['method'],
    NavicIconsProperty = lsp_kinds['property'],
    NavicIconsField = lsp_kinds['field'],
    NavicIconsConstructor = lsp_kinds['constructor'],
    NavicIconsEnum = lsp_kinds['enum'],
    NavicIconsInterface = lsp_kinds['interface'],
    NavicIconsFunction = lsp_kinds['function'],
    NavicIconsVariable = lsp_kinds['variable'],
    NavicIconsConstant = lsp_kinds['constant'],
    NavicIconsString = lsp_kinds['string'],
    NavicIconsNumber = lsp_kinds['number'],
    NavicIconsBoolean = lsp_kinds['boolean'],
    NavicIconsArray = lsp_kinds['array'],
    NavicIconsObject = lsp_kinds['object'],
    NavicIconsKey = lsp_kinds['key'],
    NavicIconsKeyword = lsp_kinds['keyword'],
    NavicIconsNull = lsp_kinds['null'],
    NavicIconsEnumMember = lsp_kinds['enumMember'],
    NavicIconsStruct = lsp_kinds['struct'],
    NavicIconsEvent = lsp_kinds['event'],
    NavicIconsOperator = lsp_kinds['operator'],
    NavicIconsTypeParameter = lsp_kinds['typeParameter'],
    NavicText = { fg = c.fg },
    NavicSeparator = { fg = c.fg },

    -- Packer
    packerString = { fg = custom.gold },
    packerHash = { fg = c.blue },
    packerOutput = { fg = custom.purple1 },
    packerRelDate = { fg = custom.gray },
    packerSuccess = { fg = c.green },
    packerStatusSuccess = { fg = c.blue },

    -- Symbols Outline
    SymbolsOutlineConnector = { fg = custom.gray },
    FocusedSymbol = { bg = c.bg_highlight },

    -- nvim-notify
    NotifyERRORBorder = { fg = tint(c.error, -0.6) },
    NotifyWARNBorder = { fg = tint(c.warning, -0.4) },
    NotifyINFOBorder = { fg = tint(c.info, -0.4) },
    NotifyDEBUGBorder = { fg = tint(c.hint, -0.4) },
    NotifyTRACEBorder = { fg = c.border },
    NotifyERRORIcon = { fg = c.error },
    NotifyWARNIcon = { fg = c.warning },
    NotifyINFOIcon = { fg = c.info },
    NotifyDEBUGIcon = { fg = c.hint },
    NotifyTRACEIcon = { fg = c.border },
    NotifyERRORTitle = { fg = c.error },
    NotifyWARNTitle = { fg = c.warning },
    NotifyINFOTitle = { fg = c.info },
    NotifyDEBUGTitle = { fg = c.hint },
    NotifyTRACETitle = { fg = c.border },

    -- Rainbow Delimiters
    RainbowDelimiterRed = { fg = c.red },
    RainbowDelimiterYellow = { fg = c.yellow },
    RainbowDelimiterBlue = { fg = c.blue },
    RainbowDelimiterOrange = { fg = c.orange },
    RainbowDelimiterGreen = { fg = c.green },
    RainbowDelimiterViolet = { fg = c.purple },
    RainbowDelimiterCyan = { fg = c.cyan },

    -- TS Rainbow (legacy)
    TSRainbowRed = { fg = c.red },
    TSRainbowYellow = { fg = c.yellow },
    TSRainbowBlue = { fg = c.blue },
    TSRainbowOrange = { fg = c.orange },
    TSRainbowGreen = { fg = c.green },
    TSRainbowViolet = { fg = c.purple },
    TSRainbowCyan = { fg = c.cyan },

    -- Hop
    HopNextKey = { fg = c.cyan, bold = true },
    HopNextKey1 = { fg = c.magenta, bold = true },
    HopNextKey2 = { fg = c.purple },
    HopPreview = { fg = c.yellow },
    HopUnmatched = { fg = custom.gray },

    -- Flash
    FlashLabel = { fg = c.cyan, bold = true, italic = true },
    FlashCurrent = { fg = c.magenta, underline = true },
    FlashMatch = { fg = c.purple },
    FlashBackdrop = { fg = custom.gray },

    -- Crates.nvim (Rust crate versions)
    CratesNvimLoading = { fg = c.blue },
    CratesNvimVersion = { fg = c.blue },

    -- Lazy.nvim
    LazyH1 = { bg = c.blue, fg = c.bg, bold = true },
    LazyButton = { bg = c.bg_highlight, fg = c.fg },
    LazyButtonActive = { bg = c.bg_visual, fg = c.fg, bold = true },
    LazyComment = { fg = c.comment },
    LazyCommit = { fg = c.green },
    LazyCommitIssue = { fg = c.blue },
    LazyCommitScope = { fg = c.purple },
    LazyCommitType = { fg = c.cyan },
    LazyDimmed = { fg = c.comment },
    LazyDir = { fg = c.blue },
    LazyH2 = { fg = c.cyan, bold = true },
    LazyLocal = { fg = c.magenta },
    LazyNoCond = { fg = c.comment },
    LazyNormal = { fg = c.fg, bg = c.bg_float },
    LazyProgressDone = { fg = c.green, bold = true },
    LazyProgressTodo = { fg = c.fg_gutter },
    LazyProp = { fg = c.orange },
    LazyReasonCmd = { fg = c.yellow },
    LazyReasonEvent = { fg = c.purple },
    LazyReasonFt = { fg = c.blue },
    LazyReasonKeys = { fg = c.cyan },
    LazyReasonPlugin = { fg = c.green },
    LazyReasonRuntime = { fg = c.orange },
    LazyReasonSource = { fg = c.magenta },
    LazyReasonStart = { fg = c.green },
    LazySpecial = { fg = c.blue },
    LazyTaskError = { fg = c.error },
    LazyTaskOutput = { fg = c.fg },
    LazyUrl = { fg = c.blue, underline = true },
    LazyValue = { fg = c.orange },

    -- Mini.nvim
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { bg = c.bg_highlight },
    MiniCursorwordCurrent = { bg = c.bg_highlight },
    MiniIndentscopeSymbol = { fg = c.blue },
    MiniIndentscopePrefix = { nocombine = true },
    MiniJump = { bg = c.magenta, fg = c.bg },
    MiniJump2dSpot = { fg = c.magenta, bold = true, nocombine = true },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { fg = c.yellow, italic = true },
    MiniStarterHeader = { fg = c.blue },
    MiniStarterInactive = { fg = c.comment },
    MiniStarterItem = { fg = c.fg, bg = c.bg },
    MiniStarterItemBullet = { fg = c.border },
    MiniStarterItemPrefix = { fg = c.warning },
    MiniStarterSection = { fg = c.cyan },
    MiniStarterQuery = { fg = c.info },
    MiniStatuslineDevinfo = { fg = c.fg_dark, bg = c.bg_highlight },
    MiniStatuslineFileinfo = { fg = c.fg_dark, bg = c.bg_highlight },
    MiniStatuslineFilename = { fg = c.fg_dark, bg = c.bg_dark },
    MiniStatuslineInactive = { fg = c.blue, bg = c.bg_statusline },
    MiniStatuslineModeCommand = { fg = c.black, bg = c.yellow, bold = true },
    MiniStatuslineModeInsert = { fg = c.black, bg = c.green, bold = true },
    MiniStatuslineModeNormal = { fg = c.black, bg = c.blue, bold = true },
    MiniStatuslineModeOther = { fg = c.black, bg = c.cyan, bold = true },
    MiniStatuslineModeReplace = { fg = c.black, bg = c.red, bold = true },
    MiniStatuslineModeVisual = { fg = c.black, bg = c.magenta, bold = true },
    MiniSurround = { bg = c.orange, fg = c.black },
    MiniTablineCurrent = { fg = c.fg, bg = c.bg_highlight },
    MiniTablineFill = { bg = c.black },
    MiniTablineHidden = { fg = c.fg_dark, bg = c.bg_statusline },
    MiniTablineModifiedCurrent = { fg = c.warning, bg = c.bg_highlight },
    MiniTablineModifiedHidden = { fg = c.warning, bg = c.bg_statusline },
    MiniTablineModifiedVisible = { fg = c.warning, bg = c.bg_statusline },
    MiniTablineTabpagesection = { fg = c.bg_statusline, bg = c.fg_gutter },
    MiniTablineVisible = { fg = c.fg, bg = c.bg_statusline },
    MiniTestEmphasis = { bold = true },
    MiniTestFail = { fg = c.red, bold = true },
    MiniTestPass = { fg = c.green, bold = true },
    MiniTrailspace = { bg = c.red },

    -- Noice
    NoiceCompletionItemKindDefault = { fg = c.fg_dark, bg = c.none },
    NoiceCompletionItemKindVariable = lsp_kinds['variable'],
    NoiceCompletionItemKindModule = lsp_kinds['module'],
    NoiceCompletionItemKindSnippet = lsp_kinds['snippet'],
    NoiceCompletionItemKindFolder = lsp_kinds['folder'],
    NoiceCompletionItemKindColor = lsp_kinds['color'],
    NoiceCompletionItemKindFile = lsp_kinds['file'],
    NoiceCompletionItemKindText = lsp_kinds['text'],
    NoiceCompletionItemKindMethod = lsp_kinds['method'],
    NoiceCompletionItemKindFunction = lsp_kinds['function'],
    NoiceCompletionItemKindConstructor = lsp_kinds['constructor'],
    NoiceCompletionItemKindField = lsp_kinds['field'],
    NoiceCompletionItemKindProperty = lsp_kinds['property'],
    NoiceCompletionItemKindUnit = lsp_kinds['unit'],
    NoiceCompletionItemKindValue = lsp_kinds['value'],
    NoiceCompletionItemKindEnum = lsp_kinds['enum'],
    NoiceCompletionItemKindKeyword = lsp_kinds['keyword'],
    NoiceCompletionItemKindReference = lsp_kinds['reference'],
    NoiceCompletionItemKindConstant = lsp_kinds['constant'],
    NoiceCompletionItemKindStruct = lsp_kinds['struct'],
    NoiceCompletionItemKindEvent = lsp_kinds['event'],
    NoiceCompletionItemKindOperator = lsp_kinds['operator'],
    NoiceCompletionItemKindNamespace = lsp_kinds['namespace'],
    NoiceCompletionItemKindPackage = lsp_kinds['package'],
    NoiceCompletionItemKindString = lsp_kinds['string'],
    NoiceCompletionItemKindNumber = lsp_kinds['number'],
    NoiceCompletionItemKindBoolean = lsp_kinds['boolean'],
    NoiceCompletionItemKindArray = lsp_kinds['array'],
    NoiceCompletionItemKindObject = lsp_kinds['object'],
    NoiceCompletionItemKindKey = lsp_kinds['key'],
    NoiceCompletionItemKindNull = lsp_kinds['null'],
    NoiceCompletionItemKindEnumMember = lsp_kinds['enumMember'],
    NoiceCompletionItemKindClass = lsp_kinds['class'],
    NoiceCompletionItemKindInterface = lsp_kinds['interface'],
    NoiceCompletionItemKindTypeParameter = lsp_kinds['typeParameter'],

    -- Trouble
    TroubleText = { fg = c.fg_dark },
    TroubleCount = { fg = c.magenta, bg = c.bg_highlight },
    TroubleNormal = { fg = c.fg, bg = c.bg_sidebar },

    -- Illuminate
    IlluminatedWordText = { bg = c.bg_highlight },
    IlluminatedWordRead = { bg = c.bg_highlight },
    IlluminatedWordWrite = { bg = c.bg_highlight },

    -- diff
    diffAdded = { fg = c.git.add },
    diffRemoved = { fg = c.git.delete },
    diffChanged = { fg = c.git.change },
    diffOldFile = { fg = c.yellow },
    diffNewFile = { fg = c.orange },
    diffFile = { fg = c.blue },
    diffLine = { fg = c.comment },
    diffIndexLine = { fg = c.magenta },

    -- Neogit
    NeogitBranch = { fg = c.magenta },
    NeogitRemote = { fg = c.purple },
    NeogitHunkHeader = { bg = c.bg_highlight, fg = c.fg },
    NeogitHunkHeaderHighlight = { bg = c.bg_visual, fg = c.blue },
    NeogitDiffContextHighlight = { bg = c.bg_dark, fg = c.fg_dark },
    NeogitDiffDeleteHighlight = { fg = c.git.delete, bg = c.diff.delete },
    NeogitDiffAddHighlight = { fg = c.git.add, bg = c.diff.add },

    -- Leap
    LeapMatch = { bg = c.magenta, fg = c.bg, bold = true },
    LeapLabelPrimary = { fg = c.cyan, bold = true },
    LeapLabelSecondary = { fg = c.green, bold = true },
    LeapBackdrop = { fg = c.comment },

    -- Dashboard
    DashboardShortCut = { fg = c.cyan },
    DashboardHeader = { fg = c.blue },
    DashboardCenter = { fg = c.magenta },
    DashboardFooter = { fg = c.yellow, italic = true },
    DashboardKey = { fg = c.orange },
    DashboardDesc = { fg = c.cyan },
    DashboardIcon = { fg = c.cyan, bold = true },

    -- Alpha (dashboard)
    AlphaShortcut = { fg = c.orange },
    AlphaHeader = { fg = c.blue },
    AlphaHeaderLabel = { fg = c.cyan },
    AlphaFooter = { fg = c.yellow, italic = true },
    AlphaButtons = { fg = c.cyan },

    -- Aerial
    AerialLine = { bg = c.bg_visual, bold = true },
    AerialGuide = { fg = c.fg_gutter },
    AerialArrayIcon = lsp_kinds['array'],
    AerialBooleanIcon = lsp_kinds['boolean'],
    AerialClassIcon = lsp_kinds['class'],
    AerialConstantIcon = lsp_kinds['constant'],
    AerialConstructorIcon = lsp_kinds['constructor'],
    AerialEnumIcon = lsp_kinds['enum'],
    AerialEnumMemberIcon = lsp_kinds['enumMember'],
    AerialEventIcon = lsp_kinds['event'],
    AerialFieldIcon = lsp_kinds['field'],
    AerialFileIcon = lsp_kinds['file'],
    AerialFunctionIcon = lsp_kinds['function'],
    AerialInterfaceIcon = lsp_kinds['interface'],
    AerialKeyIcon = lsp_kinds['key'],
    AerialKeywordIcon = lsp_kinds['keyword'],
    AerialMethodIcon = lsp_kinds['method'],
    AerialModuleIcon = lsp_kinds['module'],
    AerialNamespaceIcon = lsp_kinds['namespace'],
    AerialNullIcon = lsp_kinds['null'],
    AerialNumberIcon = lsp_kinds['number'],
    AerialObjectIcon = lsp_kinds['object'],
    AerialOperatorIcon = lsp_kinds['operator'],
    AerialPackageIcon = lsp_kinds['package'],
    AerialPropertyIcon = lsp_kinds['property'],
    AerialStringIcon = lsp_kinds['string'],
    AerialStructIcon = lsp_kinds['struct'],
    AerialTypeParameterIcon = lsp_kinds['typeParameter'],
    AerialVariableIcon = lsp_kinds['variable'],

    -- Neotest
    NeotestPassed = { fg = c.green },
    NeotestRunning = { fg = c.yellow },
    NeotestFailed = { fg = c.red },
    NeotestSkipped = { fg = c.blue },
    NeotestTest = { fg = c.fg_sidebar },
    NeotestNamespace = { fg = c.cyan },
    NeotestFocused = { bold = true },
    NeotestFile = { fg = c.cyan },
    NeotestDir = { fg = c.blue },
    NeotestBorder = { fg = c.border },
    NeotestIndent = { fg = c.fg_sidebar },
    NeotestExpandMarker = { fg = c.fg_sidebar },
    NeotestAdapterName = { fg = c.purple, bold = true },
    NeotestWinSelect = { fg = c.blue, bold = true },
    NeotestMarked = { fg = c.orange, bold = true },
    NeotestTarget = { fg = c.blue },
    NeotestUnknown = { fg = c.fg_dark },
  }
end

return M
