#!/usr/bin/env sh

yabai -m config external_bar all:24:0

# global settings
yabai -m config mouse_follows_focus             off
yabai -m config focus_follows_mouse             off
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off
yabai -m config window_shadow                   off
yabai -m config window_border                   off
yabai -m config window_border_placement         exterior
yabai -m config window_border_width             0
yabai -m config window_border_radius            0
yabai -m config active_window_border_color      0xFFF0DFA7
yabai -m config normal_window_border_color      0xB2282828
yabai -m config insert_window_border_color      0xB2EBDBB2
yabai -m config window_opacity                  off
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    on
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     2
yabai -m config bottom_padding                  2
yabai -m config left_padding                    2
yabai -m config right_padding                   2
yabai -m config window_gap                      2

yabai -m config window_topmost                  on
yabai -m config window_shadow                   float

# Space labels
yabai -m space 1 --label "Primary"
yabai -m space 2 --label "Kitty"

yabai -m space 3 --label "Browser"
yabai -m space 4 --label "Comms"
yabai -m space 5 --label "Tools"
yabai -m space 6 --label "Media"
yabai -m space 7 --label "Social"
yabai -m space 8 --label "Float"
yabai -m space 9 --label "Secondary"

# Space config
yabai -m config --space 1 layout float

# Unmanaged
yabai -m rule --add app="^System Preferences$"  manage=off border=off
yabai -m rule --add app="Harvest"               manage=off border=off
yabai -m rule --add app="ScreenFlow 9"          manage=off border=off

# Primary
yabai -m rule --add app="Brave Browser"         space=3
yabai -m rule --add app="Safari"                space=3
yabai -m rule --add app="kitty"                 space=2 border=off native-fullscreen=on
yabai -m rule --add app="Preview"               space=1

# Communication
yabai -m rule --add app="Mattermost"            space=4
yabai -m rule --add app="Notes"                 space=4
yabai -m rule --add app="Mail"                  space=4
yabai -m rule --add app="Messages"              space=4

# Tools
yabai -m rule --add app="Finder"                space=1
yabai -m rule --add app="Activity Monitor"      space=5
yabai -m rule --add app="App Store"             space=5
yabai -m rule --add app="Transmission"            space=3
yabai -m rule --add app="Terminal"              space=3

# Media
yabai -m rule --add app="Music"                 space=6
yabai -m rule --add app="QuickTime Player"      space=6
yabai -m rule --add app="TIDAL"                 space=6

# Social
yabai -m rule --add app="WhatsApp"              space=7
yabai -m rule --add app="Telegram"              space=7

# Floating
yabai -m rule --add app="^System Preferences$"  space=9
yabai -m rule --add app="ScreenFlow 9"          space=9

