commandLine:
  modeNormal:
    fg: red
  modeCommand:
    fg: green
  playStatus:
    fg: blue
  nowPlayingArtist:
    fg: cyan
  nowPlayingTitle:
    fg: magenta
  time:
    fg: yellow
  completions:
    bg: black
  completionSelected:
    bg: brightBlack

songDetail:
  border:
    fg: blue
  artistIndices:
    fg: cyan
  albumIndex:
    fg: yellow
  songTitle:
    fg: blue
  artistsText:
    fg: cyan
  albumText:
    fg: blue
  albumItem:
    border:
      fg: blue
    pageName:
      fg: blue
    albumRight:
      fg: blue
    artistRight:
      fg: cyan
    genreRight:
      fg: green
  artistItem:
    border:
      fg: cyan
    pageName:
      fg: cyan
    artistRight:
      fg: cyan
    genreRight:
      fg: green
    albumsRight:
      fg: blue

recommendationDetail:
  border:
    fg: blue
  albumsText:
    fg: blue
  albumIndices:
    fg: blue
  stationsText:
    fg: magenta
  stationIndices:
    fg: magenta
  playlistsText:
    fg: yellow
  playlistIndices:
    fg: yellow
  albumItem:
    border:
      fg: blue
    pageName:
      fg: blue
    albumRight:
      fg: blue
    artistRight:
      fg: cyan
    genreRight:
      fg: green
  playlistItem:
    border:
      fg: yellow
    pageName:
      fg: yellow
    playlistRight:
      fg: yellow
    curatorRight:
      fg: blue
    descriptionRight:
      fg: green
  stationItem:
    border:
      fg: magenta
    pageName:
      fg: magenta
    stationRight:
      fg: magenta
    isLiveRight:
      fg: blue
    notesRight:
      fg: green


artistDetail:
  border:
    fg: blue
  topSongIndices:
    fg: cyan
  albumIndices:
    fg: blue
  artistTitle:
    fg: blue
  topSongsText:
    fg: cyan
  albumsText:
    fg: blue
  albumItem:
    border:
      fg: blue
    pageName:
      fg: blue
    albumRight:
      fg: blue
    artistRight:
      fg: cyan
    genreRight:
      fg: green
  songItem:
    border:
      fg: cyan
    pageName:
      fg: cyan
    songRight:
      fg: magenta
    albumRight:
      fg: blue
    artistRight:
      fg: cyan

albumDetail:
  border:
    fg: blue
  artistsText:
    fg: cyan
  artistIndices:
    fg: cyan
  songsText:
    fg: blue
  songIndices:
    fg: blue
  songItem:
    border:
      fg: blue
    pageName:
      fg: blue
    songRight:
      fg: magenta
    albumRight:
      fg: blue
    artistRight:
      fg: cyan
  artistItem:
    border:
      fg: cyan
    pageName:
      fg: cyan
    artistRight:
      fg: cyan
    genreRight:
      fg: green
    albumsRight:
      fg: blue

playlistDetail:
  border:
    fg: blue
  songIndices:
    fg: cyan
  songsText:
    fg: cyan
  songItem:
    border:
      fg: cyan
    pageName:
      fg: cyan
    songRight:
      fg: magenta
    albumRight:
      fg: blue
    artistRight:
      fg: cyan

nowPlaying:
  page:
    fg: yellow
  pageName:
    fg: blue
  border:
    fg: blue
  songRight:
    fg: magenta
  albumRight:
    fg: blue
  artistRight:
    fg: cyan
  controls:
    fg: blue
  sliderKnob:
    fg: blue
  duration:
    fg: yellow
  currentTime:
    fg: yellow

search:
  border:
    fg: red
  pageName:
    fg: red
  itemIndices:
    fg: cyan
  albumItem:
    border:
      fg: blue
    pageName:
      fg: blue
    albumRight:
      fg: blue
    artistRight:
      fg: cyan
    genreRight:
      fg: green

  artistItem:
    border:
      fg: cyan
    pageName:
      fg: cyan
    artistRight:
      fg: cyan
    genreRight:
      fg: green
    albumsRight:
      fg: blue

  playlistItem:
    border:
      fg: yellow
    pageName:
      fg: yellow
    playlistRight:
      fg: yellow
    curatorRight:
      fg: blue
    descriptionRight:
      fg: green

  stationItem:
    border:
      fg: magenta
    pageName:
      fg: magenta
    stationRight:
      fg: magenta
    isLiveRight:
      fg: blue
    notesRight:
      fg: green
      
  songItem:
    border:
      fg: cyan
    pageName:
      fg: cyan
    songRight:
      fg: magenta
    albumRight:
      fg: blue
    artistRight:
      fg: cyan

  recommendationItem:
    border:
      fg: red
    pageName:
      fg: red
    titleRight:
      fg: red
    refreshDateRight:
      fg: green
    typesRight:
      fg: cyan
    

queue:
  border:
    fg: magenta
  pageName:
    fg: magenta
  shuffleMode:
    fg: magenta
  repeatMode:
    fg: magenta
  songItem:
    border:
      fg: blue
    pageName:
      fg: blue
    songRight:
      fg: magenta
    albumRight:
      fg: blue
    artistRight:
      fg: cyan