defaults:
  date_format: '%d/%m'
  first_day_of_week: 6
  period: week
  plot_marker: braille
  round_decimals: 2
hotkeys:
  categories:
    browse_defaults: b
    new_subcategory: s
  delete: d
  edit: e
  home:
    advance_filter: f
    budgets: b
    cycle_offset_type: .
    cycle_tabs: c
    datemode:
      go_to_day: g
    display_by_date: q
    display_by_person: w
    new_transfer: t
    select_next_account: ']'
    select_prev_account: '['
    toggle_income_mode: /
    toggle_splits: s
    toggle_use_account: \
  new: a
  record_modal:
    delete_last_split: ctrl+d
    new_paid_split: ctrl+shift+a
    new_split: ctrl+a
    submit_and_template: ctrl+t
  toggle_jump_mode: v
state:
  budgeting:
    income_assess_fallback: 3500
    income_assess_metric: periodIncome
    income_assess_threshold: 100
    savings_amount: 0
    savings_assess_metric: percentagePeriodIncome
    savings_percentage: 0.2
    wants_spending_amount: 0
    wants_spending_assess_metric: percentageQuota
    wants_spending_percentage: 0.2
  check_for_updates: true
  footer_visibility: true
  theme: gruvbox
symbols:
  amount_negative: '-'
  amount_positive: +
  category_color: "\u25CF"
  finish_line_char: "\u2570"
  line_char: "\u2502"
  split_paid: "\u2713"
  split_unpaid: "\u2A2F"
