#!/usr/bin/env bash
set -e
git --no-pager diff $1 | mods -f 'perform a code review on this source. List out any logical flaws or bugs you find, ranked in order of severity with the most sever issues presented first. When you spot a bug or issue, please always suggest a remediation. Include code snippets only when necessary to understand the issue. Does the code follow common coding conventions and idioms for the language used? Does it include appropiate tests? If not, suggest initial tests that could be added.' | glow -p -


# vim: ft=bash
