#!/bin/bash

# Script to preview files of various types

preview_file() {
    local file="$1"
    # get just the filename without path
    local filename=$(basename "$file")
    # get just the filename without extension
    local filename_no_ext="${filename%.*}"
    case "${file##*.}" in
    txt | md | log | cfg | ini | json)
        # Preview text files
        bat "$file"
        ;;
    jpg | jpeg | png | gif)
        # Preview images using timg
        timg -p s "$file"
        echo ''
        ;;
    docx)
        # Convert docx to pdf and preview using timg
        rm -rf "$HOME/tmp/disp/_soffice/*"
        soffice --headless --convert-to 'pdf:writer_pdf_Export:{"PageRange":{"type":"string","value":"1"}}' "$file" --outdir $HOME/tmp/disp/_soffice/ >/dev/null 2>&1
        pdf_file="$HOME/tmp/disp/soffice.pdf"
        mv "$HOME/tmp/disp/_soffice/$filename_no_ext.pdf" "$pdf_file"
        timg -p q "$pdf_file"
        echo ''
        ;;
    pdf)
        # Preview images using timg
        timg "$file"
        ;;
    mp3 | wav | flac)
        # Preview audio files
        mpv "$file"
        ;;
    mp4 | mkv | avi)
        # Preview video files
        mpv "$file"
        ;;
    *)
        echo "Unsupported file type: $file"
        ;;
    esac
}

# Check if at least one argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 <file1> <file2> ..."
    exit 1
fi

# Iterate over provided files and preview them
for file in "$@"; do
    if [ -f "$file" ]; then
        preview_file "$file"
    else
        echo "File not found: $file"
    fi
done

# vim: ft=bash
