#!/bin/bash
[[ -f "$HOME/.dotfiles/scripts/machine-env.sh" ]] && source "$HOME/.dotfiles/scripts/machine-env.sh"

export PATH="$HOMEBREW_PREFIX/bin:$PATH"
# export NVIM_SOCKET_PATH=/tmp/nvim-mcp.sock
export NVIM_SOCKET_PATH=/tmp/nvim-mcp-server.sock
export ALLOW_SHELL_COMMANDS=true
exec npx -y mcp-neovim-server
