# btop config (curated)
color_theme = "gruvbox"
theme_background = True
truecolor = True

vim_keys = True
rounded_corners = True
graph_symbol = "braille"

shown_boxes = "cpu mem net proc"
update_ms = 2000

proc_sorting = "memory"
proc_mem_bytes = True
proc_cpu_graphs = True

cpu_invert_lower = True
show_uptime = True
check_temp = True
show_coretemp = True
temp_scale = "celsius"
show_cpu_freq = True
clock_format = "%X"

mem_graphs = True
show_swap = True
swap_disk = True
show_disks = True
only_physical = True
use_fstab = True
show_io_stat = True

net_auto = True
