prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:pr is:open archived:false sort:updated-desc user:akinsho
  - title: Neovim Issues
    filters: is:open repo:neovim/neovim
issuesSections:
  - title: My Open Source Projects
    filters: is:issue is:open archived:false sort:updated-desc user:akinsho
  - title: My Issues
    filters: is:open author:@me
  - title: Neovim Issues
    filters: is:open repo:neovim/neovim
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: issues
repoPaths:
  neovim/neovim: $PROJECTS_DIR/contributing/neovim
  akinsho/bufferline.nvim: $PROJECTS_DIR/personal/bufferline.nvim
  akinsho/toggleterm.nvim: $PROJECTS_DIR/personal/bufferline.nvim
keybindings:
  prs:
    - key: c
      command: kitty @ launch --cwd={{.RepoPath}} zsh -c 'gh pr checkout {{.PrNumber}}; nvim'
