-- Base Vim highlight groups for Dracula Pro

local M = {}

function M.get(c, opts)
  return {
    Comment = { fg = c.comment, style = opts.styles.comments },
    ColorColumn = { bg = c.black },
    Conceal = { fg = c.fg_dark },
    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = { fg = c.bg, bg = c.fg },
    CursorIM = { fg = c.bg, bg = c.fg },
    CursorColumn = { bg = c.bg_highlight },
    CursorLine = { bg = c.bg_highlight },
    Directory = { fg = c.blue },
    DiffAdd = { bg = c.diff.add },
    DiffChange = { bg = c.diff.change },
    DiffDelete = { bg = c.diff.delete },
    DiffText = { bg = c.diff.text },
    EndOfBuffer = { fg = c.bg },
    ErrorMsg = { fg = c.error },
    VertSplit = { fg = c.border },
    WinSeparator = { fg = c.border, bold = true },
    Folded = { fg = c.blue, bg = c.fg_gutter },
    FoldColumn = { bg = opts.transparent and c.none or c.bg, fg = c.comment },
    SignColumn = { bg = opts.transparent and c.none or c.bg, fg = c.fg_gutter },
    SignColumnSB = { bg = c.bg_sidebar, fg = c.fg_gutter },
    Substitute = { bg = c.red, fg = c.black },
    LineNr = { fg = c.fg_gutter },
    CursorLineNr = { fg = c.orange, bold = true },
    LineNrAbove = { fg = c.fg_gutter },
    LineNrBelow = { fg = c.fg_gutter },
    MatchParen = { fg = c.orange, bold = true },
    ModeMsg = { fg = c.fg_dark, bold = true },
    MsgArea = { fg = c.fg_dark },
    MoreMsg = { fg = c.blue },
    NonText = { fg = c.fg_dark },
    Normal = { fg = c.fg, bg = opts.transparent and c.none or c.bg },
    NormalNC = {
      fg = c.fg,
      bg = opts.transparent and c.none
        or opts.dim_inactive and c.bg_dark
        or c.bg,
    },
    NormalSB = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    NormalFloat = { fg = c.fg_float, bg = c.bg_float },
    FloatBorder = { fg = c.border_highlight, bg = c.bg_float },
    FloatTitle = { fg = c.border_highlight, bg = c.bg_float },
    Pmenu = { bg = c.bg_popup, fg = c.fg },
    PmenuSel = { bg = c.bg_visual },
    PmenuSbar = { bg = c.bg_popup },
    PmenuThumb = { bg = c.fg_gutter },
    Question = { fg = c.blue },
    QuickFixLine = { bg = c.bg_visual, bold = true },
    Search = { bg = c.bg_search, fg = c.fg },
    IncSearch = { bg = c.orange, fg = c.black },
    CurSearch = 'IncSearch',
    SpecialKey = { fg = c.fg_dark },
    SpellBad = { sp = c.error, undercurl = true },
    SpellCap = { sp = c.warning, undercurl = true },
    SpellLocal = { sp = c.info, undercurl = true },
    SpellRare = { sp = c.hint, undercurl = true },
    StatusLine = { fg = c.fg_sidebar, bg = c.bg_statusline },
    StatusLineNC = { fg = c.fg_gutter, bg = c.bg_statusline },
    TabLine = { bg = c.bg_statusline, fg = c.fg_gutter },
    TabLineFill = { bg = opts.transparent and c.none or c.black },
    TabLineSel = { fg = c.black, bg = c.blue },
    Title = { fg = c.blue, bold = true },
    Visual = { bg = c.bg_visual },
    VisualNOS = { bg = c.bg_visual },
    WarningMsg = { fg = c.warning },
    Whitespace = { fg = c.fg_gutter },
    WildMenu = { bg = c.bg_visual },
    WinBar = 'StatusLine',
    WinBarNC = 'StatusLineNC',

    Bold = { bold = true, fg = c.fg },
    Character = { fg = c.syntax_string },
    Constant = { fg = c.syntax_constant },
    Debug = { fg = c.orange },
    Delimiter = 'Special',
    Error = { fg = c.error },
    Function = { fg = c.syntax_function, style = opts.styles.functions },
    Identifier = { fg = c.syntax_variable, style = opts.styles.variables },
    Italic = { italic = true, fg = c.fg },
    Keyword = { fg = c.syntax_keyword, style = opts.styles.keywords },
    Operator = { fg = c.blue5 },
    PreProc = { fg = c.cyan },
    Special = { fg = c.blue1 },
    Statement = { fg = c.magenta },
    String = { fg = c.syntax_string },
    Todo = { bg = c.yellow, fg = c.bg },
    Type = { fg = c.syntax_class },
    Underlined = { underline = true },

    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warning },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticUnnecessary = { fg = c.comment },
    DiagnosticVirtualTextError = { fg = c.error, bg = c.none },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = c.none },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.none },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.none },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },

    LspReferenceText = { bg = c.bg_highlight },
    LspReferenceRead = { bg = c.bg_highlight },
    LspReferenceWrite = { bg = c.bg_highlight },
    LspSignatureActiveParameter = { bg = c.bg_visual, bold = true },
    LspCodeLens = { fg = c.comment },
    LspInlayHint = { fg = c.comment, bg = c.none },

    GitGutterAdd = { fg = c.git.add },
    GitGutterChange = { fg = c.git.change },
    GitGutterDelete = { fg = c.git.delete },
    GitSignsAdd = { fg = c.git.add },
    GitSignsChange = { fg = c.git.change },
    GitSignsDelete = { fg = c.git.delete },
  }
end

return M
