-- Treesitter highlight groups for Dracula Pro

local M = {}

function M.get(c, opts)
  return {
    ['@annotation'] = 'PreProc',
    ['@attribute'] = 'PreProc',
    ['@boolean'] = 'Boolean',
    ['@character'] = 'Character',
    ['@character.printf'] = 'SpecialChar',
    ['@character.special'] = 'SpecialChar',
    ['@comment'] = 'Comment',
    ['@comment.error'] = { fg = c.error },
    ['@comment.hint'] = { fg = c.hint },
    ['@comment.info'] = { fg = c.info },
    ['@comment.note'] = { fg = c.hint },
    ['@comment.todo'] = { fg = c.todo },
    ['@comment.warning'] = { fg = c.warning },
    ['@constant'] = 'Constant',
    ['@constant.builtin'] = 'Special',
    ['@constant.macro'] = 'Define',
    ['@constructor'] = { fg = c.magenta },
    ['@constructor.tsx'] = { fg = c.blue1 },
    ['@diff.delta'] = 'DiffChange',
    ['@diff.minus'] = 'DiffDelete',
    ['@diff.plus'] = 'DiffAdd',
    ['@function'] = 'Function',
    ['@function.builtin'] = 'Special',
    ['@function.call'] = '@function',
    ['@function.macro'] = 'Macro',
    ['@function.method'] = 'Function',
    ['@function.method.call'] = '@function.method',
    ['@keyword'] = { fg = c.purple, style = opts.styles.keywords },
    ['@keyword.conditional'] = 'Conditional',
    ['@keyword.coroutine'] = '@keyword',
    ['@keyword.debug'] = 'Debug',
    ['@keyword.directive'] = 'PreProc',
    ['@keyword.directive.define'] = 'Define',
    ['@keyword.exception'] = 'Exception',
    ['@keyword.function'] = { fg = c.magenta, style = opts.styles.functions },
    ['@keyword.import'] = 'Include',
    ['@keyword.operator'] = '@operator',
    ['@keyword.repeat'] = 'Repeat',
    ['@keyword.return'] = '@keyword',
    ['@keyword.storage'] = 'StorageClass',
    ['@label'] = { fg = c.blue },
    ['@markup'] = '@none',
    ['@markup.emphasis'] = { italic = true },
    ['@markup.environment'] = 'Macro',
    ['@markup.environment.name'] = 'Type',
    ['@markup.heading'] = 'Title',
    ['@markup.italic'] = { italic = true },
    ['@markup.link'] = { fg = c.teal },
    ['@markup.link.label'] = 'SpecialChar',
    ['@markup.link.label.symbol'] = 'Identifier',
    ['@markup.link.url'] = 'Underlined',
    ['@markup.list'] = { fg = c.blue5 },
    ['@markup.list.checked'] = { fg = c.green },
    ['@markup.list.markdown'] = { fg = c.orange, bold = true },
    ['@markup.list.unchecked'] = { fg = c.blue },
    ['@markup.math'] = 'Special',
    ['@markup.raw'] = 'String',
    ['@markup.raw.markdown_inline'] = { bg = c.terminal_black, fg = c.blue },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.strong'] = { bold = true },
    ['@markup.underline'] = { underline = true },
    ['@module'] = 'Include',
    ['@module.builtin'] = { fg = c.red },
    ['@namespace.builtin'] = '@variable.builtin',
    ['@none'] = {},
    ['@number'] = 'Number',
    ['@number.float'] = 'Float',
    ['@operator'] = { fg = c.blue5 },
    ['@property'] = { fg = c.cyan },
    ['@punctuation.bracket'] = { fg = c.fg_dark },
    ['@punctuation.delimiter'] = { fg = c.blue5 },
    ['@punctuation.special'] = { fg = c.blue5 },
    ['@string'] = 'String',
    ['@string.documentation'] = { fg = c.green },
    ['@string.escape'] = { fg = c.magenta },
    ['@string.regexp'] = { fg = c.blue },
    ['@tag'] = { fg = c.red },
    ['@tag.attribute'] = { fg = c.cyan },
    ['@tag.delimiter'] = { fg = c.fg_dark },
    ['@tag.delimiter.tsx'] = { fg = c.blue },
    ['@tag.tsx'] = { fg = c.red },
    ['@type'] = 'Type',
    ['@type.builtin'] = { fg = c.cyan },
    ['@type.definition'] = 'Typedef',
    ['@type.qualifier'] = '@keyword',
    ['@variable'] = { fg = c.fg, style = opts.styles.variables },
    ['@variable.builtin'] = { fg = c.red },
    ['@variable.member'] = { fg = c.cyan },
    ['@variable.parameter'] = { fg = c.orange },

    ['@lsp.type.boolean'] = '@boolean',
    ['@lsp.type.builtinType'] = '@type.builtin',
    ['@lsp.type.comment'] = '@comment',
    ['@lsp.type.decorator'] = '@attribute',
    ['@lsp.type.deriveHelper'] = '@attribute',
    ['@lsp.type.enum'] = '@type',
    ['@lsp.type.enumMember'] = '@constant',
    ['@lsp.type.escapeSequence'] = '@string.escape',
    ['@lsp.type.formatSpecifier'] = '@markup.list',
    ['@lsp.type.generic'] = '@variable',
    ['@lsp.type.interface'] = { fg = c.blue1 },
    ['@lsp.type.keyword'] = '@keyword',
    ['@lsp.type.lifetime'] = '@storageclass',
    ['@lsp.type.namespace'] = '@namespace',
    ['@lsp.type.number'] = '@number',
    ['@lsp.type.operator'] = '@operator',
    ['@lsp.type.parameter'] = '@variable.parameter',
    ['@lsp.type.property'] = '@property',
    ['@lsp.type.selfKeyword'] = '@variable.builtin',
    ['@lsp.type.selfTypeKeyword'] = '@variable.builtin',
    ['@lsp.type.string'] = '@string',
    ['@lsp.type.typeAlias'] = '@type.definition',
    ['@lsp.type.unresolvedReference'] = { undercurl = true, sp = c.error },
    ['@lsp.type.variable'] = {},
    ['@lsp.typemod.class.defaultLibrary'] = '@type.builtin',
    ['@lsp.typemod.enum.defaultLibrary'] = '@type.builtin',
    ['@lsp.typemod.enumMember.defaultLibrary'] = '@constant.builtin',
    ['@lsp.typemod.function.defaultLibrary'] = '@function.builtin',
    ['@lsp.typemod.keyword.async'] = '@keyword.coroutine',
    ['@lsp.typemod.keyword.injected'] = '@keyword',
    ['@lsp.typemod.macro.defaultLibrary'] = '@function.builtin',
    ['@lsp.typemod.method.defaultLibrary'] = '@function.builtin',
    ['@lsp.typemod.operator.injected'] = '@operator',
    ['@lsp.typemod.string.injected'] = '@string',
    ['@lsp.typemod.struct.defaultLibrary'] = '@type.builtin',
    ['@lsp.typemod.type.defaultLibrary'] = { fg = c.cyan },
    ['@lsp.typemod.typeAlias.defaultLibrary'] = { fg = c.cyan },
    ['@lsp.typemod.variable.callable'] = '@function',
    ['@lsp.typemod.variable.defaultLibrary'] = '@variable.builtin',
    ['@lsp.typemod.variable.injected'] = '@variable',
    ['@lsp.typemod.variable.static'] = '@constant',
  }
end

return M
